### ISSUE TITLE
NMP https://github.com/MyEtherWallet/MEWcon

### ISSUE THREAD

**Issue by BLACKMAGICBTC** [MyEtherWallet/MEWconnect-web-client#168]

**Comment by BLACKMAGICBTC** [comment]
https://developer.trustwallet.com/assets/requirements`
Asset details
Token Name
Symbol
Contract Address
Decimals
BNB or TWT to cover the non-refundable [processing fee](https://github.com/assets/pr-fee)
Logo
File Extension: png (Uppercase PNG is considered invalid)
File Name: logo.png
Size: 256px by 256px
Background: Preferably transparent
Token information file
File Extension: json (Uppercase JSON is considered invalid)
File Name: info.json
Required fields:
name: name of the token
type: such as ERC20, BEP2, BEP20, TRC20, TRC10, ...
symbol: the token symbol
decimals: number of decimal digits used in the amounts (e.g. 18 for ETH)
description: a few sentence summary of the token/project
website: project web site
explorer: URL of the token explorer page
id: the id/contract/address of the token, same as the subfolder name
links: array with name/url pairs, for social media links, documentation, etc.
tags: Assigning these tags to tokens helps place them on appropriate token menus and ensures your token is evaluated correctly in conditions.
Checksum address (for ERC20 and BEP20 tokens)

**Comment by ztodnano** [comment]
rjii
