### ISSUE TITLE
No error thrown when the QR model is closed

### ISSUE THREAD

**Issue by xiaowheat** [MyEtherWallet/MEWconnect-web-client#19]
<img width="444" alt="Screen Shot 2020-08-20 at 9 06 15 PM" src="https://user-images.githubusercontent.com/18495858/90851335-39234b00-e329-11ea-9520-52102ae7c1b3.png">
When the QR model is closed, no error is thrown

The code is 
```
try {
        connecting = true;
        accounts = await provider.enable();
        connecting = false;
} catch (e) {

}
```

**Comment by kvhnuke** [comment]
this should be fixed now, let me know if you still running into the same issue
