### ISSUE TITLE
Make keepAlive optional

### ISSUE THREAD

**Issue by bogdan** [MyEtherWallet/MEWconnect-web-client#60]
`keepAlive` functionality in web3 provider feels very specific to certain providers. Is it possible to add an option to disable it?

https://github.com/MyEtherWallet/MEWconnect-web-client/blob/master/src/connectProvider/web3Provider/web3-provider/providers/ws-provider.js#L27

**Comment by kvhnuke** [comment]
fixed in ff2059f7
