### ISSUE TITLE
shibatoken@myetherwallet

### ISSUE THREAD

**Issue by TJackson88** [MyEtherWallet/MEWconnect-web-client#63]
[![image](https://user-images.githubusercontent.com/86429424/125215657-ae6d7680-e281-11eb-99ca-41cf1add947c.png)]()

**Comment by TJackson88** [comment]
@TJackson88

**Comment by TJackson88** [comment]
**ShibaSwap**

**Comment by TJackson88** [comment]
@Foboz @gsiuniak @hsurf22 @kvhnuke @gesseekur @gamalielhere @rsteubs

**Comment by TJackson88** [comment]
[tjackson88.eth]()

**Comment by kvhnuke** [comment]
spam
